### ISSUE TITLE
你好，红包不能自动开吗

### ISSUE THREAD

**Issue by LarrySha** [Amoryan/WeworkAccessibility#3]
我试了下 1840微信只能到开红包界面，不能自动打开

**Comment by Amoryan** [comment]
微信上红包封面上获取是有点问题的，我自己的设备调的时候也遇到过，因为拿root node有问题。我换了种方式获取，这台电脑上没有签名文件，打不了包，你自己打个包验证下，或者等我晚上回家了重新打个包，你再看下。

**Comment by Amoryan** [comment]
apk 已经更新了，可以下载试试
